FROM python:3.12-slim

LABEL description="Dockerfile for training the loan approval predictor model"

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY pyproject.toml .
COPY src/ src/

RUN pip install .

COPY train/ train/
COPY datasets/ datasets/
COPY MLproject .

CMD ["mlflow", "run", ".", "--env-manager", "local"]